version: '3'
services:
  backend:
    build: ./server
    container_name: backend
    ports:
      - 3000:3000
    command: npm run start:dev
    restart: always
  frontend:
    build: ./client
    container_name: frontend
    ports:
      - 80:80
    restart: always

